import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appName: 'KrishiBazar',
    appTagline: 'Direct Farmer-to-Farmer Agri Marketplace',
    searchPlaceholder: 'Search crops, plants, seeds, fertilizer...',
    searchSimplePlaceholder: 'Search crops, plants, seeds, fertilizer...',
    directContactOnly: '100% Direct Contact • No Online Payment • 0% Commission',
    directContactSub: 'Connect directly with local farmers via Call or WhatsApp. Inspect goods physically before buying.',
    callFarmer: 'Call Farmer',
    whatsAppSeller: 'WhatsApp',
    shareListing: 'Share',
    saveListing: 'Save',
    saved: 'Saved',
    allCategories: 'Categories',
    home: 'Home',
    sell: 'Sell Item',
    myAds: 'My Ads',
    featuredDeals: 'Urgent Farmer Harvest & Deals',
    topSeeds: 'High-Yield Certified Seeds',
    machineryImplements: 'Tractors & Heavy Machinery',
    organicFertilizers: 'Organic Compost & Nutrients',
    viewAll: 'View All',
    price: 'Price',
    negotiable: 'Negotiable',
    fixedPrice: 'Fixed Price',
    condition: 'Condition',
    availableStock: 'Stock',
    minOrder: 'Min. Order',
    harvestDate: 'Harvest / Mfg Year',
    specifications: 'Technical Specifications & Lab Data',
    sellerInfo: 'Farmer / Seller Details',
    villageLocation: 'Village & Mandi Location',
    memberSince: 'Member Since',
    verifiedFarmer: 'Verified Farmer',
    safetyNoticeTitle: 'Farmer Deal Safety Advice',
    safetyNotice1: 'Always inspect machinery, seeds, or crops in person at farm or local mandi before payment.',
    safetyNotice2: 'Never transfer advance token money online without meeting the seller.',
    safetyNotice3: 'Verify seed lab certification tags and tractor registration certificates (RC).',
    safetyNotice4: 'KrishiBazar does not take commission or process payments. All transactions are direct between buyer and seller.',
    postAdTitle: 'Sell Farm Produce / Machinery Free',
    postAdSubtitle: 'Share directly with 50,000+ local farmers. Free listing.',
    stepCategory: '1. Select Category',
    stepDetails: '2. Product Details',
    stepPrice: '3. Price & Stock',
    stepContact: '4. Contact Details',
    productTitle: 'Product / Item Title',
    productTitlePlaceholder: 'e.g. Fursungi Onion Seedlings (1,000 Plants)',
    selectCategory: 'Select Category',
    itemCondition: 'Item Condition',
    newCondition: 'Brand New / Sealed',
    usedCondition: 'Used / Second Hand',
    certifiedSeed: 'Certified Seed / Nursery',
    organicProduce: '100% Organic Farm Produce',
    pricePerUnit: 'Price (in ₹)',
    unitLabel: 'Unit (e.g. Crate, Quintal, Tray, Bag)',
    quantityPlaceholder: 'e.g. 50 Crates or 100 Quintals',
    description: 'Detailed Description & Farming Tips',
    farmerName: 'Your Full Name',
    phoneNumber: 'Mobile Phone Number',
    whatsAppNumber: 'WhatsApp Number',
    state: 'State',
    district: 'District',
    village: 'Village / Mandi Name',
    pincode: 'Pincode',
    submitListing: 'Publish Listing Free',
    listingCreatedSuccess: 'Your listing is live on KrishiBazar!',
    noSavedItems: 'No saved listings yet',
    noSavedItemsSub: 'Bookmark seeds, machinery, and crops to quickly call farmers later.',
    noListingsYet: 'You have not posted any listings yet',
    noListingsYetSub: 'Have surplus seeds, harvest, or used machinery? Post an ad in 2 minutes.',
    mandiPriceTicker: 'Live Mandi Bhav',
    safetyGuide: 'Safe Trading Guide',
    filterBy: 'Filter By',
    sortBy: 'Sort By',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    newestFirst: 'Newest First',
    onlyVerified: 'Verified Farmers Only',
    onlyOrganic: 'Organic Certified Only',
    clearAll: 'Clear All',
    applyFilters: 'Apply Filters',
    contactFarmerModalTitle: 'Connect with Farmer',
    directCallDesc: 'Tap below to call directly on mobile network:',
    whatsAppDesc: 'Or start a direct chat on WhatsApp with pre-filled message:',
    copyNumber: 'Copy Number',
    numberCopied: 'Phone number copied!',
    backToHome: 'Back to Home',
    relatedProducts: 'Similar Items in this Category',
    viewSellerProfile: 'View Farmer Profile',
    otherListingsByFarmer: 'Other Listings by this Farmer',
    dealsCount: 'Direct Deals',
    rating: 'Rating',

    // New Sections & Navigation
    popularProducts: 'Popular Farm Produce & Inputs',
    popularProductsSub: 'High demand seedlings, certified seeds, fodder & tools',
    nearbyFarmers: 'Nearby Farmers & Mandi Stock',
    nearbyFarmersSub: 'Verified produce available near your location',
    orders: 'Orders',
    search: 'Search',
    profile: 'Profile',
    account: 'Account',
    myAccount: 'Farmer Account',
    kisanCard: 'Digital Kisan ID Card',
    notifications: 'Notifications',
    checkout: 'Confirm Order & Contact Seller',
    totalAmount: 'Total Estimated Value',
    directFarmerPickup: 'Direct Farm Visit & Inspection',
    mandiPickup: 'Pickup at Nearest Mandi Yard',
    sellerDelivery: 'Seller Tractor/Tempo Delivery',
    kmAway: 'km away',

    // Auth & Account
    login: 'Farmer Login',
    logout: 'Logout',
    register: 'Register Farmer',
    kisanId: 'Kisan ID',
    enterMobile: 'Enter 10-Digit Mobile Number',
    sendOtp: 'Send Verification OTP',
    verifyOtp: 'Verify OTP & Login',
    otpSentTo: 'Enter 4-digit code sent to',
    autoFillOtp: '⚡ Auto-fill Test Code (5566)',
    loginWithPin: 'Login with PIN',
    loginWithOtp: 'Login with Mobile OTP',
    quickDemoLogin: '1-Tap Demo Farmer Login',
    selectDemoProfile: 'Select a verified profile to test instantly:',
    enterPin: '4-Digit Security PIN',
    defaultPinHint: 'Default PIN is 1234',
    dontHaveAccount: 'New to KrishiBazar?',
    alreadyHaveAccount: 'Already have an account?',
    registerNow: 'Register as New Farmer',
    loginNow: 'Login to Account',
    farmType: 'Farming Specialty & Crops',
    landSize: 'Land Acreage (e.g. 20 Acres)',
    createKisanAccount: 'Create Verified Kisan Profile',
    logoutConfirmTitle: 'Logout of KrishiBazar?',
    logoutConfirmDesc: 'You can log back in anytime with your mobile number or security PIN.',
    confirmLogout: 'Yes, Logout',
    cancel: 'Cancel',
    loggedInAs: 'Logged in as',
    activeListings: 'Active Ads',
    savedItems: 'Saved Items',
    editProfile: 'Edit Farm Info',
    kisanHelpline: 'Kisan Call Center: 1800-180-1551',
    welcomeBack: 'Welcome back,',
    guestFarmer: 'Guest Farmer',
    loginToPost: 'Login to post and manage your agricultural listings faster.',
    switchFarmer: 'Switch Profile / Demo',
    resendOtp: 'Resend OTP'
  },
  hi: {
    appName: 'कृषि बाज़ार',
    appTagline: 'किसानों का सीधा कृषि बाज़ार (खरीदें व बेचें)',
    searchPlaceholder: 'फसल, पौधे, बीज, खाद, उपकरण खोजें...',
    searchSimplePlaceholder: 'फसल, पौधे, बीज, खाद, उपकरण खोजें...',
    directContactOnly: '100% सीधा संपर्क • कोई ऑनलाइन भुगतान नहीं • 0% कमीशन',
    directContactSub: 'कॉल या व्हाट्सएप से सीधे किसान से बात करें। सामान देखकर ही भुगतान करें।',
    callFarmer: 'कॉल करें',
    whatsAppSeller: 'व्हाट्सएप',
    shareListing: 'शेयर',
    saveListing: 'सेव',
    saved: 'सेव किया',
    allCategories: 'सभी श्रेणियां',
    home: 'होम',
    sell: 'सामान बेचें',
    myAds: 'मेरी लिस्टिंग',
    featuredDeals: 'ताजा फसल व जरूरी ऑफर',
    topSeeds: 'उच्च पैदावार प्रमाणित बीज',
    machineryImplements: 'ट्रैक्टर व कृषि यंत्र',
    organicFertilizers: 'जैविक खाद एवं पोषक तत्व',
    viewAll: 'सभी देखें',
    price: 'मूल्य',
    negotiable: 'मोलभाव संभव',
    fixedPrice: 'तय मूल्य',
    condition: 'स्थिति',
    availableStock: 'उपलब्ध स्टॉक',
    minOrder: 'न्यूनतम आर्डर',
    harvestDate: 'फसल/निर्माण वर्ष',
    specifications: 'तकनीकी जानकारी व लैब डेटा',
    sellerInfo: 'किसान / विक्रेता विवरण',
    villageLocation: 'गाँव व नजदीकी मंडी',
    memberSince: 'सदस्य बने',
    verifiedFarmer: 'सत्यापित किसान',
    safetyNoticeTitle: 'सुरक्षित किसान व्यापार सलाह',
    safetyNotice1: 'मशीनरी, बीज या फसल की जांच हमेशा खेत या नजदीकी मंडी में स्वयं जाकर करें।',
    safetyNotice2: 'सामान देखने से पहले कभी भी ऑनलाइन टोकन राशि ट्रांसफर न करें।',
    safetyNotice3: 'बीज प्रमाणन टैग और ट्रैक्टर के आरसी/बीमा कागजात अवश्य जांचें।',
    safetyNotice4: 'कृषि बाज़ार कोई कमीशन या ऑनलाइन पेमेंट नहीं लेता। सभी सौदे सीधे किसान और खरीदार के बीच होते हैं।',
    postAdTitle: 'फसल, बीज या कृषि यंत्र निशुल्क बेचें',
    postAdSubtitle: '50,000+ स्थानीय किसान भाइयों तक सीधा पहुंचाएं। 0% कमीशन।',
    stepCategory: '1. श्रेणी चुनें',
    stepDetails: '2. सामान का विवरण',
    stepPrice: '3. मूल्य व स्टॉक',
    stepContact: '4. संपर्क विवरण',
    productTitle: 'सामान / फसल का नाम',
    productTitlePlaceholder: 'जैसे: फुर्सुंगी प्याज पौध (1,000 पौधे)',
    selectCategory: 'श्रेणी चुनें',
    itemCondition: 'सामान की स्थिति',
    newCondition: 'बिल्कुल नया / सीलबंद',
    usedCondition: 'पुराना / सेकेंड हैंड',
    certifiedSeed: 'प्रमाणित बीज / नर्सरी पौध',
    organicProduce: '100% जैविक उत्पाद',
    pricePerUnit: 'मूल्य (₹ में)',
    unitLabel: 'इकाई (जैसे: क्रेट, क्विंटल, ट्रे, बोरी)',
    quantityPlaceholder: 'जैसे: 50 क्रेट या 100 क्विंटल',
    description: 'विवरण एवं उपयोग सलाह',
    farmerName: 'आपका पूरा नाम',
    phoneNumber: 'मोबाइल नंबर (कॉल हेतु)',
    whatsAppNumber: 'व्हाट्सएप नंबर',
    state: 'राज्य',
    district: 'जिला',
    village: 'गाँव / मंडी का नाम',
    pincode: 'पिनकोड',
    submitListing: 'निशुल्क लिस्टिंग पोस्ट करें',
    listingCreatedSuccess: 'आपकी लिस्टिंग कृषि बाज़ार पर प्रकाशित हो गई है!',
    noSavedItems: 'अभी कोई सेव की गई लिस्टिंग नहीं है',
    noSavedItemsSub: 'पसंदीदा बीज और मशीनों को सेव करें ताकि बाद में आसानी से किसान को कॉल कर सकें।',
    noListingsYet: 'आपने अभी कोई लिस्टिंग पोस्ट नहीं की है',
    noListingsYetSub: 'अतिरिक्त बीज, बंपर फसल या पुराना ट्रैक्टर बेचना चाहते हैं? 2 मिनट में विज्ञापन डालें।',
    mandiPriceTicker: 'लाइव मंडी भाव',
    safetyGuide: 'सुरक्षित व्यापार मार्गदर्शिका',
    filterBy: 'फ़िल्टर करें',
    sortBy: 'क्रमबद्ध करें',
    priceLowToHigh: 'मूल्य: कम से ज्यादा',
    priceHighToLow: 'मूल्य: ज्यादा से कम',
    newestFirst: 'नवीनतम पहले',
    onlyVerified: 'केवल सत्यापित किसान',
    onlyOrganic: 'केवल प्रमाणित जैविक',
    clearAll: 'रीसेट करें',
    applyFilters: 'फ़िल्टर लागू करें',
    contactFarmerModalTitle: 'किसान से सीधा संपर्क',
    directCallDesc: 'मोबाइल नेटवर्क पर सीधी बात करने के लिए टैप करें:',
    whatsAppDesc: 'या व्हाट्सएप पर तुरंत चैट शुरू करें:',
    copyNumber: 'नंबर कॉपी करें',
    numberCopied: 'मोबाइल नंबर कॉपी हो गया!',
    backToHome: 'होम पर वापस जाएं',
    relatedProducts: 'इस श्रेणी के अन्य उत्पाद',
    viewSellerProfile: 'किसान प्रोफाइल देखें',
    otherListingsByFarmer: 'इस किसान की अन्य लिस्टिंग',
    dealsCount: 'सफल सौदे',
    rating: 'रेटिंग',

    // New Sections & Navigation
    popularProducts: 'लोकप्रिय शेतमाल एवं कृषि उत्पाद',
    popularProductsSub: 'प्याज पौध, मिर्च, चारा, उत्तम बीज व कृषि यंत्र',
    nearbyFarmers: 'नजदीकी किसान एवं मंडी का माल',
    nearbyFarmersSub: 'आपके क्षेत्र के आसपास उपलब्ध सत्यापित शेतमाल',
    orders: 'ऑर्डर्स',
    search: 'खोजें',
    profile: 'प्रोफाइल',
    account: 'खाता',
    myAccount: 'किसान खाता',
    kisanCard: 'डिजिटल किसान कार्ड',
    notifications: 'सूचनाएं',
    checkout: 'ऑर्डर पक्का करें व किसान से बात करें',
    totalAmount: 'कुल अनुमानित मूल्य',
    directFarmerPickup: 'खेत पर जाकर स्वयं माल देखें',
    mandiPickup: 'नजदीकी मंडी से उठाव',
    sellerDelivery: 'विक्रेता द्वारा ट्रैक्टर/टेंपो से डिलीवरी',
    kmAway: 'किमी दूर',

    // Auth & Account
    login: 'किसान लॉगिन',
    logout: 'लॉगआउट करें',
    register: 'किसान पंजीकरण',
    kisanId: 'किसान आईडी',
    enterMobile: '10 अंकों का मोबाइल नंबर दर्ज करें',
    sendOtp: 'ओटीपी (OTP) भेजें',
    verifyOtp: 'ओटीपी सत्यापित करें',
    otpSentTo: 'इस नंबर पर भेजा गया कोड दर्ज करें:',
    autoFillOtp: '⚡ टेस्ट कोड भरें (5566)',
    loginWithPin: 'पिन (PIN) से लॉगिन करें',
    loginWithOtp: 'मोबाइल ओटीपी से लॉगिन करें',
    quickDemoLogin: '1-टैप डेमो किसान लॉगिन',
    selectDemoProfile: 'तुरंत टेस्ट करने के लिए सत्यापित किसान चुनें:',
    enterPin: '4 अंकों का सुरक्षा पिन',
    defaultPinHint: 'डिफ़ॉल्ट पिन 1234 है',
    dontHaveAccount: 'क्या आप नए किसान हैं?',
    alreadyHaveAccount: 'पहले से पंजीकृत हैं?',
    registerNow: 'नया किसान पंजीकरण करें',
    loginNow: 'सीधा लॉगिन करें',
    farmType: 'मुख्य फसलें एवं कृषि कार्य',
    landSize: 'खेत का रकबा / ज़मीन (जैसे: 20 एकड़)',
    createKisanAccount: 'किसान कार्ड व प्रोफ़ाइल बनाएं',
    logoutConfirmTitle: 'क्या आप लॉगआउट करना चाहते हैं?',
    logoutConfirmDesc: 'आप अपने मोबाइल नंबर या 4 अंकों के पिन से कभी भी दोबारा लॉगिन कर सकते हैं।',
    confirmLogout: 'हाँ, लॉगआउट करें',
    cancel: 'रद्द करें',
    loggedInAs: 'सक्रिय किसान:',
    activeListings: 'सक्रिय विज्ञापन',
    savedItems: 'सेव किए गए सामान',
    editProfile: 'कृषि जानकारी बदलें',
    kisanHelpline: 'किसान कॉल सेंटर: 1800-180-1551',
    welcomeBack: 'राम-राम,',
    guestFarmer: 'अतिथि किसान',
    loginToPost: 'अपने विज्ञापनों को आसानी से प्रबंधित करने के लिए लॉगिन करें।',
    switchFarmer: 'प्रोफाइल बदलें',
    resendOtp: 'दोबारा ओटीपी भेजें'
  },
  mr: {
    appName: 'कृषी बाझार',
    appTagline: 'शेतकऱ्यांचा थेट कृषी बाजार (खरेदी आणि विक्री)',
    searchPlaceholder: 'शेतमाल, रोपे, बियाणे, खते, अवजारे शोधा...',
    searchSimplePlaceholder: 'शेतमाल, रोपे, बियाणे, खते, अवजारे शोधा...',
    directContactOnly: '१००% थेट संपर्क • ऑनलाइन पेमेंट नाही • ०% कमिशन',
    directContactSub: 'कॉल किंवा व्हॉट्सॲपवरून थेट शेतकऱ्यांशी संपर्क साधा. मालाची प्रत्यक्ष पाहणी करूनच व्यवहार करा.',
    callFarmer: 'कॉल करा',
    whatsAppSeller: 'व्हॉट्सॲप',
    shareListing: 'शेअर',
    saveListing: 'जतन',
    saved: 'जतन केलेले',
    allCategories: 'सर्व श्रेणी',
    home: 'मुख्यपृष्ठ',
    sell: 'वस्तू विका',
    myAds: 'माझ्या जाहिराती',
    featuredDeals: 'ताजी पिके व तातडीच्या ऑफर्स',
    topSeeds: 'उत्कृष्ट दर्जाचे प्रमाणित बियाणे',
    machineryImplements: 'ट्रॅक्टर व कृषी अवजारे',
    organicFertilizers: 'सेंद्रिय खते व पोषक घटक',
    viewAll: 'सर्व पहा',
    price: 'किंमत',
    negotiable: 'दर वाटाघाटी शक्य',
    fixedPrice: 'निश्चित दर',
    condition: 'स्थिती',
    availableStock: 'उपलब्ध साठा',
    minOrder: 'किमान ऑर्डर',
    harvestDate: 'हंगाम / उत्पादन वर्ष',
    specifications: 'तांत्रिक तपशील व लॅब माहिती',
    sellerInfo: 'शेतकरी / विक्रेता तपशील',
    villageLocation: 'गाव व जवळची बाजार समिती',
    memberSince: 'सदस्यता',
    verifiedFarmer: 'सत्यापित शेतकरी',
    safetyNoticeTitle: 'सुरक्षित शेतकरी व्यवहाराचे नियम',
    safetyNotice1: 'ट्रॅक्टर, बियाणे किंवा शेतमालाची तपासणी नेहमी शेतात किंवा बाजार समितीत जाऊन स्वतः करा.',
    safetyNotice2: 'माल पाहण्यापूर्वी कधीही ऑनलाइन आगाऊ रक्कम (टोकन) पाठवू नका.',
    safetyNotice3: 'बियाणे प्रमाणीकरण टॅग आणि वाहनाचे आरसी/कागदपत्रे नीट तपासा.',
    safetyNotice4: 'कृषी बाझार कोणतेही कमिशन घेत नाही. सर्व व्यवहार थेट शेतकरी आणि ग्राहक यांच्यात होतात.',
    postAdTitle: 'शेतमाल, बियाणे किंवा अवजारे मोफत विका',
    postAdSubtitle: '५०,०००+ स्थानिक शेतकरी बांधवांपर्यंत मोफत जाहिरात पोहोचवा. ०% कमिशन.',
    stepCategory: '१. वर्ग निवडा',
    stepDetails: '२. वस्तूचा तपशील',
    stepPrice: '३. किंमत व साठा',
    stepContact: '४. संपर्क माहिती',
    productTitle: 'वस्तू / पिकाचे नाव',
    productTitlePlaceholder: 'उदा. फुर्सुंगी कांदा रोपे (१,००० रोपे)',
    selectCategory: 'वर्ग निवडा',
    itemCondition: 'वस्तूची स्थिती',
    newCondition: 'अगदी नवीन / सीलबंद',
    usedCondition: 'वापरलेले / जुने यंत्र',
    certifiedSeed: 'प्रमाणित बियाणे / रोपवाटिका',
    organicProduce: '१००% सेंद्रिय शेतमाल',
    pricePerUnit: 'किंमत (₹ मध्ये)',
    unitLabel: 'एकक (उदा. क्रेट, क्विंटल, ट्रे, पोते)',
    quantityPlaceholder: 'उदा. ५० क्रेट किंवा १०० क्विंटल',
    description: 'सविस्तर माहिती व वापराचा सल्ला',
    farmerName: 'तुमचे पूर्ण नाव',
    phoneNumber: 'मोबाईल नंबर (कॉलसाठी)',
    whatsAppNumber: 'व्हॉट्सॲप नंबर',
    state: 'राज्य',
    district: 'जिल्हा',
    village: 'गाव / बाजार समिती',
    pincode: 'पिनकोड',
    submitListing: 'मोफत जाहिरात पोस्ट करा',
    listingCreatedSuccess: 'तुमची जाहिरात कृषी बाझारवर प्रसिद्ध झाली आहे!',
    noSavedItems: 'अद्याप कोणतीही जाहिरात जतन केलेली नाही',
    noSavedItemsSub: 'आवडीचे बियाणे आणि यंत्रे जतन करा जेणेकरून नंतर सहज संपर्क करता येईल.',
    noListingsYet: 'तुम्ही अजून कोणतीही जाहिरात दिलेली नाही',
    noListingsYetSub: 'शेतमाल, बियाणे किंवा जुना ट्रॅक्टर विकायचा आहे? २ मिनिटांत मोफत जाहिरात द्या.',
    mandiPriceTicker: 'बाजार समिती थेट भाव',
    safetyGuide: 'सुरक्षित खरेदी-विक्री मार्गदर्शक',
    filterBy: 'फिल्टर',
    sortBy: 'क्रमवारी',
    priceLowToHigh: 'किंमत: कमी ते जास्त',
    priceHighToLow: 'किंमत: जास्त ते कमी',
    newestFirst: 'नवीनतम आधी',
    onlyVerified: 'केवळ सत्यापित शेतकरी',
    onlyOrganic: 'केवळ प्रमाणित सेंद्रिय',
    clearAll: 'रीसेट करा',
    applyFilters: 'फिल्टर लागू करा',
    contactFarmerModalTitle: 'शेतकऱ्याशी थेट संपर्क',
    directCallDesc: 'थेट फोनवर बोलण्यासाठी खाली टॅप करा:',
    whatsAppDesc: 'किंवा व्हॉट्सॲपवर त्वरित संदेश पाठवा:',
    copyNumber: 'नंबर कॉपी करा',
    numberCopied: 'मोबाईल नंबर कॉपी झाला!',
    backToHome: 'मुख्यपृष्ठावर जा',
    relatedProducts: 'या श्रेणीतील इतर उत्पादने',
    viewSellerProfile: 'शेतकरी प्रोफाइल पहा',
    otherListingsByFarmer: 'या शेतकऱ्याची इतर उत्पादने',
    dealsCount: 'यशस्वी व्यवहार',
    rating: 'रेटिंग',

    // New Sections & Navigation
    popularProducts: 'लोकप्रिय शेतमाल व उत्पादने',
    popularProductsSub: 'कांदा रोपे, मिरची, मका चारा, बियाणे व अवजारे',
    nearbyFarmers: 'जवळचे शेतकरी व बाजार समिती माल',
    nearbyFarmersSub: 'तुमच्या परिसरातील खात्रीशीर शेतमाल',
    orders: 'ऑर्डर्स',
    search: 'शोधा',
    profile: 'प्रोफाइल',
    account: 'खाते',
    myAccount: 'शेतकरी खाते',
    kisanCard: 'डिजिटल शेतकरी ओळखपत्र',
    notifications: 'सूचना',
    checkout: 'ऑर्डर निश्चित करा व संपर्क साधा',
    totalAmount: 'एकूण अंदाजे रक्कम',
    directFarmerPickup: 'शेतात प्रत्यक्ष जाऊन पाहणी',
    mandiPickup: 'जवळच्या बाजार समितीतून',
    sellerDelivery: 'विक्रेत्याकडून ट्रॅक्टर/टेम्पोने डिलिव्हरी',
    kmAway: 'किमी लांब',

    // Auth & Account
    login: 'शेतकरी लॉगिन',
    logout: 'बाहेर पडा (Logout)',
    register: 'शेतकरी नोंदणी',
    kisanId: 'शेतकरी ओळख क्रमांक',
    enterMobile: '१० अंकी मोबाईल नंबर टाका',
    sendOtp: 'ओटीपी (OTP) पाठवा',
    verifyOtp: 'ओटीपी तपासा आणि लॉगिन करा',
    otpSentTo: 'या नंबरवर पाठवलेला कोड टाका:',
    autoFillOtp: '⚡ टेस्ट कोड भरा (5566)',
    loginWithPin: 'पिन (PIN) ने लॉगिन करा',
    loginWithOtp: 'मोबाईल ओटीपीने लॉगिन करा',
    quickDemoLogin: '१-टॅप डेमो शेतकरी लॉगिन',
    selectDemoProfile: 'तपासणीसाठी सत्यापित शेतकरी निवडा:',
    enterPin: '४ अंकी सुरक्षा पिन',
    defaultPinHint: 'डीफॉल्ट पिन 1234 आहे',
    dontHaveAccount: 'तुम्ही नवीन शेतकरी आहात का?',
    alreadyHaveAccount: 'आधीच नोंदणी केली आहे का?',
    registerNow: 'नवीन शेतकरी नोंदणी करा',
    loginNow: 'थेट लॉगिन करा',
    farmType: 'मुख्य पिके व शेतीचा प्रकार',
    landSize: 'एकूण जमीन (उदा. १५ एकर)',
    createKisanAccount: 'शेतकरी ओळखपत्र बनवा',
    logoutConfirmTitle: 'बाहेर पडायचे आहे का?',
    logoutConfirmDesc: 'तुम्ही तुमच्या मोबाईल नंबर किंवा पिनने कधीही पुन्हा लॉगिन करू शकता.',
    confirmLogout: 'हो, बाहेर पडा',
    cancel: 'रद्द करा',
    loggedInAs: 'सक्रिय शेतकरी:',
    activeListings: 'सक्रिय जाहिराती',
    savedItems: 'जतन केलेल्या वस्तू',
    editProfile: 'शेती माहिती बदला',
    kisanHelpline: 'शेतकरी कॉल सेंटर: 1800-180-1551',
    welcomeBack: 'नमस्कार शेतकरी बांधव,',
    guestFarmer: 'अतिथी शेतकरी',
    loginToPost: 'तुमच्या जाहिराती सहज पाहण्यासाठी लॉगिन करा.',
    switchFarmer: 'प्रोफाइल बदला',
    resendOtp: 'पुन्हा ओटीपी पाठवा'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
