import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appName: 'KrishiBazar',
    appTagline: 'Direct Farmer-to-Farmer Agri Marketplace',
    searchPlaceholder: 'Search seeds, tractors, fertilizer, crops...',
    directContactOnly: '100% Direct Contact • No Online Payment • 0% Commission',
    directContactSub: 'Connect directly with local farmers via Call or WhatsApp. Inspect goods physically before buying.',
    callFarmer: 'Call Farmer',
    whatsAppSeller: 'WhatsApp Seller',
    shareListing: 'Share',
    saveListing: 'Save',
    saved: 'Saved',
    allCategories: 'Categories',
    home: 'Home',
    sell: 'Sell Item',
    myAds: 'My Ads',
    featuredDeals: 'Urgent Farmer Harvest & Deals',
    topSeeds: 'High-Yield Certified Seeds',
    machineryImplements: 'Tractors & Heavy Machinery',
    organicFertilizers: 'Organic Compost & Nutrients',
    viewAll: 'View All',
    price: 'Price',
    negotiable: 'Negotiable',
    fixedPrice: 'Fixed Price',
    condition: 'Condition',
    availableStock: 'Available Stock',
    minOrder: 'Min. Order',
    harvestDate: 'Harvest / Mfg Year',
    specifications: 'Technical Specifications & Lab Data',
    sellerInfo: 'Seller / Farmer Details',
    villageLocation: 'Village & Mandi Location',
    memberSince: 'Member Since',
    verifiedFarmer: 'Verified Farmer',
    safetyNoticeTitle: 'Farmer Deal Safety Advice',
    safetyNotice1: 'Always inspect machinery, seeds, or crops in person at farm or local mandi before payment.',
    safetyNotice2: 'Never transfer advance token money online without meeting the seller.',
    safetyNotice3: 'Verify seed lab certification tags and tractor registration certificates (RC).',
    safetyNotice4: 'KrishiBazar does not take commission or process payments. All transactions are direct between buyer and seller.',
    postAdTitle: 'Sell Your Farm Produce / Machinery',
    postAdSubtitle: 'Share directly with 50,000+ local farmers. Free listing.',
    stepCategory: '1. Select Category',
    stepDetails: '2. Product Details',
    stepPrice: '3. Price & Stock',
    stepContact: '4. Contact Details',
    productTitle: 'Product / Item Title',
    productTitlePlaceholder: 'e.g. Sharbati Wheat Seeds HD-2967 (40 kg bag)',
    selectCategory: 'Select Category',
    itemCondition: 'Item Condition',
    newCondition: 'Brand New / Sealed',
    usedCondition: 'Used / Second Hand',
    certifiedSeed: 'Certified Seed',
    organicProduce: '100% Organic Farm Produce',
    pricePerUnit: 'Price (in ₹)',
    unitLabel: 'Unit (e.g. kg, Quintal, Piece, Bag)',
    quantityPlaceholder: 'e.g. 50 Quintals or 1 Unit',
    description: 'Detailed Description & Usage Tips',
    farmerName: 'Your Full Name',
    phoneNumber: 'Mobile Phone Number (for calling)',
    whatsAppNumber: 'WhatsApp Number',
    state: 'State',
    district: 'District',
    village: 'Village / Mandi Name',
    pincode: 'Pincode',
    submitListing: 'Publish Listing Free',
    listingCreatedSuccess: 'Your listing is live on KrishiBazar!',
    noSavedItems: 'No saved listings yet',
    noSavedItemsSub: 'Bookmark seeds, machinery, and crops to quickly call farmers later.',
    noListingsYet: 'You have not posted any listings yet',
    noListingsYetSub: 'Have surplus seeds, harvest, or used machinery? Post an ad in 2 minutes.',
    mandiPriceTicker: 'Live Mandi Bhav',
    safetyGuide: 'Safe Trading Guide',
    filterBy: 'Filter By',
    sortBy: 'Sort By',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    newestFirst: 'Newest First',
    onlyVerified: 'Verified Farmers Only',
    onlyOrganic: 'Organic Certified Only',
    clearAll: 'Clear All',
    applyFilters: 'Apply Filters',
    contactFarmerModalTitle: 'Connect with Farmer',
    directCallDesc: 'Tap below to call directly on mobile network:',
    whatsAppDesc: 'Or start a direct chat on WhatsApp with pre-filled message:',
    copyNumber: 'Copy Number',
    numberCopied: 'Phone number copied!',
    backToHome: 'Back to Home',
    relatedProducts: 'Similar Items in this Category',
    viewSellerProfile: 'View Farmer Profile & Other Listings',
    otherListingsByFarmer: 'Other Listings by this Farmer',
    dealsCount: 'Successful Deals',
    rating: 'Rating'
  },
  hi: {
    appName: 'कृषि बाज़ार',
    appTagline: 'किसानों का सीधा कृषि बाज़ार (खरीदें व बेचें)',
    searchPlaceholder: 'बीज, ट्रैक्टर, खाद, उपकरण, फसल खोजें...',
    directContactOnly: '100% सीधा संपर्क • कोई ऑनलाइन भुगतान नहीं • 0% कमीशन',
    directContactSub: 'कॉल या व्हाट्सएप से सीधे किसान से बात करें। सामान देखकर ही भुगतान करें।',
    callFarmer: 'किसान को कॉल करें',
    whatsAppSeller: 'व्हाट्सएप पर बात करें',
    shareListing: 'शेयर करें',
    saveListing: 'सेव करें',
    saved: 'सेव किया',
    allCategories: 'श्रेणियां',
    home: 'होम',
    sell: 'सामान बेचें',
    myAds: 'मेरी लिस्टिंग',
    featuredDeals: 'ताजा फसल व जरूरी ऑफर',
    topSeeds: 'उच्च पैदावार प्रमाणित बीज',
    machineryImplements: 'ट्रैक्टर व कृषि यंत्र',
    organicFertilizers: 'जैविक खाद एवं पोषक तत्व',
    viewAll: 'सभी देखें',
    price: 'मूल्य',
    negotiable: 'मोलभाव संभव',
    fixedPrice: 'तय मूल्य',
    condition: 'स्थिति',
    availableStock: 'उपलब्ध मात्रा',
    minOrder: 'न्यूनतम आर्डर',
    harvestDate: 'फसल/निर्माण वर्ष',
    specifications: 'तकनीकी जानकारी व लैब डेटा',
    sellerInfo: 'किसान / विक्रेता विवरण',
    villageLocation: 'गाँव व नजदीकी मंडी',
    memberSince: 'सदस्य बने',
    verifiedFarmer: 'सत्यापित किसान',
    safetyNoticeTitle: 'सुरक्षित किसान व्यापार सलाह',
    safetyNotice1: 'मशीनरी, बीज या फसल की जांच हमेशा खेत या नजदीकी मंडी में स्वयं जाकर करें।',
    safetyNotice2: 'सामान देखने से पहले कभी भी ऑनलाइन टोकन राशि ट्रांसफर न करें।',
    safetyNotice3: 'बीज प्रमाणन टैग और ट्रैक्टर के आरसी/बीमा कागजात अवश्य जांचें।',
    safetyNotice4: 'कृषि बाज़ार कोई कमीशन या ऑनलाइन पेमेंट नहीं लेता। सभी सौदे सीधे किसान और खरीदार के बीच होते हैं।',
    postAdTitle: 'अपनी फसल, बीज या कृषि यंत्र बेचें',
    postAdSubtitle: '50,000+ स्थानीय किसान भाइयों तक सीधा पहुंचाएं। निशुल्क लिस्टिंग।',
    stepCategory: '1. श्रेणी चुनें',
    stepDetails: '2. सामान का विवरण',
    stepPrice: '3. मूल्य व स्टॉक',
    stepContact: '4. संपर्क विवरण',
    productTitle: 'सामान / फसल का नाम',
    productTitlePlaceholder: 'जैसे: शरबती गेहूं बीज HD-2967 (40 किग्रा बोरी)',
    selectCategory: 'श्रेणी चुनें',
    itemCondition: 'सामान की स्थिति',
    newCondition: 'बिल्कुल नया / सीलबंद',
    usedCondition: 'पुराना / सेकेंड हैंड',
    certifiedSeed: 'प्रमाणित बीज',
    organicProduce: '100% जैविक उत्पाद',
    pricePerUnit: 'मूल्य (₹ में)',
    unitLabel: 'इकाई (जैसे: किग्रा, क्विंटल, पीस, बोरी)',
    quantityPlaceholder: 'जैसे: 50 क्विंटल या 1 यूनिट',
    description: 'विवरण एवं उपयोग सलाह',
    farmerName: 'आपका पूरा नाम',
    phoneNumber: 'मोबाइल नंबर (कॉल हेतु)',
    whatsAppNumber: 'व्हाट्सएप नंबर',
    state: 'राज्य',
    district: 'जिला',
    village: 'गाँव / मंडी का नाम',
    pincode: 'पिनकोड',
    submitListing: 'निशुल्क लिस्टिंग पोस्ट करें',
    listingCreatedSuccess: 'आपकी लिस्टिंग कृषि बाज़ार पर प्रकाशित हो गई है!',
    noSavedItems: 'अभी कोई सेव की गई लिस्टिंग नहीं है',
    noSavedItemsSub: 'पसंदीदा बीज और मशीनों को सेव करें ताकि बाद में आसानी से किसान को कॉल कर सकें।',
    noListingsYet: 'आपने अभी कोई लिस्टिंग पोस्ट नहीं की है',
    noListingsYetSub: 'अतिरिक्त बीज, बंपर फसल या पुराना ट्रैक्टर बेचना चाहते हैं? 2 मिनट में विज्ञापन डालें।',
    mandiPriceTicker: 'लाइव मंडी भाव',
    safetyGuide: 'सुरक्षित व्यापार मार्गदर्शिका',
    filterBy: 'फ़िल्टर करें',
    sortBy: 'क्रमबद्ध करें',
    priceLowToHigh: 'मूल्य: कम से ज्यादा',
    priceHighToLow: 'मूल्य: ज्यादा से कम',
    newestFirst: 'नवीनतम पहले',
    onlyVerified: 'केवल सत्यापित किसान',
    onlyOrganic: 'केवल प्रमाणित जैविक',
    clearAll: 'रीसेट करें',
    applyFilters: 'फ़िल्टर लागू करें',
    contactFarmerModalTitle: 'किसान से सीधा संपर्क',
    directCallDesc: 'मोबाइल नेटवर्क पर सीधी बात करने के लिए टैप करें:',
    whatsAppDesc: 'या व्हाट्सएप पर तुरंत चैट शुरू करें:',
    copyNumber: 'नंबर कॉपी करें',
    numberCopied: 'मोबाइल नंबर कॉपी हो गया!',
    backToHome: 'होम पर वापस जाएं',
    relatedProducts: 'इस श्रेणी के अन्य उत्पाद',
    viewSellerProfile: 'किसान प्रोफाइल व अन्य सामान देखें',
    otherListingsByFarmer: 'इस किसान की अन्य लिस्टिंग',
    dealsCount: 'सफल सौदे',
    rating: 'रेटिंग'
  },
  mr: {
    appName: 'कृषी बाझार',
    appTagline: 'शेतकऱ्यांचा थेट कृषी बाजार (खरेदी आणि विक्री)',
    searchPlaceholder: 'बियाणे, ट्रॅक्टर, खते, अवजारे, शेतमाल शोधा...',
    directContactOnly: '१००% थेट संपर्क • ऑनलाइन पेमेंट नाही • ०% कमिशन',
    directContactSub: 'कॉल किंवा व्हॉट्सॲपवरून थेट शेतकऱ्यांशी संपर्क साधा. मालाची प्रत्यक्ष पाहणी करूनच व्यवहार करा.',
    callFarmer: 'शेतकऱ्याला कॉल करा',
    whatsAppSeller: 'व्हॉट्सॲपवर संपर्क साधा',
    shareListing: 'शेअर करा',
    saveListing: 'जतन करा',
    saved: 'जतन केलेले',
    allCategories: 'श्रेणी / वर्ग',
    home: 'मुख्यपृष्ठ',
    sell: 'वस्तू विका',
    myAds: 'माझ्या जाहिराती',
    featuredDeals: 'ताजी पिके व तातडीच्या ऑफर्स',
    topSeeds: 'उत्कृष्ट दर्जाचे प्रमाणित बियाणे',
    machineryImplements: 'ट्रॅक्टर व कृषी अवजारे',
    organicFertilizers: 'सेंद्रिय खते व पोषक घटक',
    viewAll: 'सर्व पहा',
    price: 'किंमत',
    negotiable: 'दर वाटाघाटी शक्य',
    fixedPrice: 'निश्चित दर',
    condition: 'स्थिती',
    availableStock: 'उपलब्ध साठा',
    minOrder: 'किमान ऑर्डर',
    harvestDate: 'हंगाम / उत्पादन वर्ष',
    specifications: 'तांत्रिक तपशील व लॅब माहिती',
    sellerInfo: 'शेतकरी / विक्रेता तपशील',
    villageLocation: 'गाव व जवळची बाजार समिती',
    memberSince: 'सदस्यता',
    verifiedFarmer: 'सत्यापित शेतकरी',
    safetyNoticeTitle: 'सुरक्षित शेतकरी व्यवहाराचे नियम',
    safetyNotice1: 'ट्रॅक्टर, बियाणे किंवा शेतमालाची तपासणी नेहमी शेतात किंवा बाजार समितीत जाऊन स्वतः करा.',
    safetyNotice2: 'माल पाहण्यापूर्वी कधीही ऑनलाइन आगाऊ रक्कम (टोकन) पाठवू नका.',
    safetyNotice3: 'बियाणे प्रमाणीकरण टॅग आणि वाहनाचे आरसी/कागदपत्रे नीट तपासा.',
    safetyNotice4: 'कृषी बाझार कोणतेही कमिशन घेत नाही. सर्व व्यवहार थेट शेतकरी आणि ग्राहक यांच्यात होतात.',
    postAdTitle: 'तुमचा शेतमाल, बियाणे किंवा अवजारे विका',
    postAdSubtitle: '५०,०००+ स्थानिक शेतकरी बांधवांपर्यंत मोफत जाहिरात पोहोचवा.',
    stepCategory: '१. वर्ग निवडा',
    stepDetails: '२. वस्तूचा तपशील',
    stepPrice: '३. किंमत व साठा',
    stepContact: '४. संपर्क माहिती',
    productTitle: 'वस्तू / पिकाचे नाव',
    productTitlePlaceholder: 'उदा. शरबती गहू बियाणे HD-2967 (४० किलो पोते)',
    selectCategory: 'वर्ग निवडा',
    itemCondition: 'वस्तूची स्थिती',
    newCondition: 'अगदी नवीन / सीलबंद',
    usedCondition: 'वापरलेले / जुने यंत्र',
    certifiedSeed: 'प्रमाणित बियाणे',
    organicProduce: '१००% सेंद्रिय शेतमाल',
    pricePerUnit: 'किंमत (₹ मध्ये)',
    unitLabel: 'एकक (उदा. किलो, क्विंटल, नग, पोते)',
    quantityPlaceholder: 'उदा. ५० क्विंटल किंवा १ नग',
    description: 'सविस्तर माहिती व वापराचा सल्ला',
    farmerName: 'तुमचे पूर्ण नाव',
    phoneNumber: 'मोबाईल नंबर (कॉलसाठी)',
    whatsAppNumber: 'व्हॉट्सॲप नंबर',
    state: 'राज्य',
    district: 'जिल्हा',
    village: 'गाव / बाजार समिती',
    pincode: 'पिनकोड',
    submitListing: 'मोफत जाहिरात पोस्ट करा',
    listingCreatedSuccess: 'तुमची जाहिरात कृषी बाझारवर प्रसिद्ध झाली आहे!',
    noSavedItems: 'अद्याप कोणतीही जाहिरात जतन केलेली नाही',
    noSavedItemsSub: 'आवडीचे बियाणे आणि यंत्रे जतन करा जेणेकरून नंतर सहज संपर्क करता येईल.',
    noListingsYet: 'तुम्ही अजून कोणतीही जाहिरात दिलेली नाही',
    noListingsYetSub: 'शेतमाल, बियाणे किंवा जुना ट्रॅक्टर विकायचा आहे? २ मिनिटांत मोफत जाहिरात द्या.',
    mandiPriceTicker: 'बाजार समिती थेट भाव',
    safetyGuide: 'सुरक्षित खरेदी-विक्री मार्गदर्शक',
    filterBy: 'फिल्टर',
    sortBy: 'क्रमवारी',
    priceLowToHigh: 'किंमत: कमी ते जास्त',
    priceHighToLow: 'किंमत: जास्त ते कमी',
    newestFirst: 'नवीनतम आधी',
    onlyVerified: 'केवळ सत्यापित शेतकरी',
    onlyOrganic: 'केवळ प्रमाणित सेंद्रिय',
    clearAll: 'रीसेट करा',
    applyFilters: 'फिल्टर लागू करा',
    contactFarmerModalTitle: 'शेतकऱ्याशी थेट संपर्क',
    directCallDesc: 'थेट फोनवर बोलण्यासाठी खाली टॅप करा:',
    whatsAppDesc: 'किंवा व्हॉट्सॲपवर त्वरित संदेश पाठवा:',
    copyNumber: 'नंबर कॉपी करा',
    numberCopied: 'मोबाईल नंबर कॉपी झाला!',
    backToHome: 'मुख्यपृष्ठावर जा',
    relatedProducts: 'या श्रेणीतील इतर उत्पादने',
    viewSellerProfile: 'शेतकरी प्रोफाइल व इतर उत्पादने पहा',
    otherListingsByFarmer: 'या शेतकऱ्याची इतर उत्पादने',
    dealsCount: 'यशस्वी व्यवहार',
    rating: 'रेटिंग'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
